### ISSUE TITLE
Abstract out toastr, dialogs, and $log into 'Message' service

### ISSUE THREAD

**Issue by jcox86** [Lotpath/Strappy#12]
These are currently 3 different services being injected into most controllers.

We should be able to combine them into a messaging service that will allow us to only inject 1 service and be used globally across app.

$log is an angular service that can put messages onto the browser console, or throw to other services, such as an API that will then email us when problems occur in the app???

**Comment by jessetechie** [comment]
Add to this service a function that will take an array of error messages and format them as an HTML list, then pass it to the dialogs.error() function.

**Comment by jcox86** [comment]
@jessetechie @jeffdoolittle @gregfiske  @Modem56k A possible future enhancement to this would be to wrap the toastr and dialog services to also write to the log every time.  When a user experiences an toastr error, it goes away.  Including $log with every toastr and dialog call would keep an accurate record of changes within the app.

We could even have the $log service post these messages to an API route and write to a database table, keeping an audit record of everything the user does....

**Comment by jessetechie** [comment]
After attempting to implement this on an actual project, it is becoming apparent that the messages service should not simply expose three properties (toastr, dialogs, and $log) but instead should encapsulate and handle the coordination between the 3.  

The obvious benefit of change management comes to mind: if/when these libraries are updated (especially the dialogs service which has undergone many changes), the message service would need to change, but application code would not.  

Another benefit would be consistency in the interface.  toastr puts title after message (because title is optional), while dialogs puts title first and uses constants for default values.  That inconsistency can be hidden away because a blank value can be given for title if it is not desired.

A third feature of this service would be to handle logging automatically based on a config option.  For now we'll turn logging on or off for all messages.

A fourth feature, and the genesis for this service, is the ability to pass an array of strings and have them formatted as an HTML unordered list 

I've begun rewriting this to provide the following functions:

- [x] success: calls toastr.success and optionally writes to $log.log
- [x] warn: calls toastr.warning and optionally writes to $log.warn
- [x] info: calls toastr.info and optionally writes to $log.info
- [x] error: calls toastr.error and optionally writes to $log.error
- [ ] notify: calls dialogs.notify and optionally writes to $log.info
- [x] confirm: calls dialogs.confirm and optionally writes to $log.info when a button is clicked.
- [ ] wait: calls dialogs.wait and optionally writes to $log.info when progress changes.
- [ ] errorDialog: calls dialogs.error and optionally writes to $log.error
- [ ] createDialog: calls dialogs.create and returns the dialog object.  Does not log automatically.
- [x] log: exposes the log object for ad-hoc logging

Future features could include: 
* individual flags for logging each type of message
* configure toastr and dialogs options globally without modifying messages-module.js (in other words, make toastr and dialogs options as properties on the message service options)
* ability to pass service options into the function, including any toastr or dialogs options.  Currently the options parameter on each function is for either the toastr or dialogs options.

**Comment by jessetechie** [comment]
Issues: 

- [ ] passing an array to a toast message requires an options object

**Comment by jeffdoolittle** [comment]
I completely agree regarding encapsulation. There's little value in a collecting object for just accessing the dependencies/services as properties.

**Comment by jessetechie** [comment]
I know, but it was so much easier!  :)

**Comment by jessetechie** [comment]
It occurred to me that creating a custom dialog is outside the scope of this service.  This is for showing messages to users, not for creating modal popups with forms in them.  If we want to create a modal, we can use angular-bootstrap's $modal directly.
